version: '3.8'

services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ./API:/src/API
      - ./API/appsettings.Development.json:/app/appsettings.Development.json
    ports:
      - "8080:8080"
      - "8081:8081"